# Ручная починка после matugen
$text_color = rgba(d9e2ffFF)
$entry_background_color = rgba(00194411)
$entry_border_color = rgba(8f909955)
$entry_color = rgba(d9e2ffFF)
$font_family = Google Sans Flex
$font_family_clock = Google Sans Flex
$font_material_symbols = Material Symbols Rounded
