general {
    lock_cmd = pidof hyprlock || hyprlock       # команда для блокировки
    before_sleep_cmd = loginctl lock-session    # блокировать перед сном (если он случится)
    after_sleep_cmd = hyprctl dispatch dpms on  # включить монитор после просыпания
}

# Через 20 минут (1200 секунд) — блокировка
listener {
    timeout = 108000
    on-timeout = loginctl lock-session
}
