general {
    immediate_render = true
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/pasha/Pictures/allwp/valley-midnight.jpg
    color = rgb(10, 20, 40)

    # настройки блюра
    blur_passes = 2
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.7
}

# --- ПОЛЕ ВВОДА С XRAY ---
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = true

    outer_color = rgba(167, 197, 252, 0.6)
    inner_color = rgba(10, 20, 40, 0.2)
    font_color = rgb(216, 226, 246)

    fade_on_empty = true
    placeholder_text = <span font_family="SF Pro Rounded">Enter Password...</span>
    hide_input = false
    rounding = 15 # скругленные углы

    position = 0, -440
    halign = center
    valign = center
}

# --- ВЕРХНЯЯ ПАНЕЛЬ ---

label { # Раскладка
  monitor =
  text = cmd[update:1000] echo "$LAYOUT"
  color = rgba(216, 226, 246, 0.75)
  font_size = 14
  font_family = SF Pro Rounded
  position = -20, -20
  halign = right
  valign = top
}

# --- ЧАСЫ И ДАТА ---

label { # Дата
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(216, 226, 246, 0.8)
  font_size = 22
  font_family = SF Pro Rounded Bold
  position = 0, 180
  halign = center
  valign = center
}

label { # Время
  monitor =
  text = $TIME
  color = rgba(216, 226, 246, 1.0)
  font_size = 95
  font_family = SF Pro Rounded Bold
  position = 0, 80
  halign = center
  valign = center
}

# --- ЮЗЕР ---

label {
    monitor =
    text = $USER
    color = rgba(216, 226, 246, 0.8)
    font_size = 16
    font_family = SF Pro Rounded Bold
    position = 0, -380
    halign = center
    valign = center
}
