general {
    immediate_render = true
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/kowk/Pictures/Assets/Wallpapers/material shapes(green)/materiallite-wallpaper-2026-03-25-2048x1152.png
    color = rgb(10, 20, 10)

    # настройки блюра
    blur_passes = 2
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.7
}

# --- ПОЛЕ ВВОДА С XRAY ---
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = true

    outer_color = rgba(74, 122, 74, 0.6)
    inner_color = rgba(10, 20, 10, 0.2)
    font_color = rgb(200, 220, 200)

    # Эффект XRAY: поле будет показывать четкие обои сквозь блюр
    xray = true

    fade_on_empty = true
    placeholder_text = <span font_family="SF Pro Display">Enter Password...</span>
    hide_input = false
    rounding = 15 # скругленные углы

    position = 0, -440
    halign = center
    valign = center
}

# --- ВЕРХНЯЯ ПАНЕЛЬ ---

label { # Музыка
  monitor =
  text = cmd[update:1000] echo "$(~/.config/Scripts/song-status)"
  color = rgba(200, 220, 200, 0.75)
  font_size = 14
  font_family = SF Pro Text
  position = 20, -20
  halign = left
  valign = top
}

label { # Раскладка
  monitor =
  text = cmd[update:1000] echo "$LAYOUT"
  color = rgba(200, 220, 200, 0.75)
  font_size = 14
  font_family = SF Pro Text
  position = -20, -20
  halign = right
  valign = top
}

# --- ЧАСЫ И ДАТА ---

label { # Дата
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(200, 220, 200, 0.8)
  font_size = 22
  font_family = SF Pro Display Bold
  position = 0, 180
  halign = center
  valign = center
}

label { # Время
  monitor =
  text = $TIME
  color = rgba(200, 220, 200, 1.0)
  font_size = 95
  font_family = SF Pro Display Bold
  position = 0, 80
  halign = center
  valign = center
}

# --- ЮЗЕР И АВАТАР ---

image {
    monitor =
    path = /home/kowk/Pictures/fullpfp.png
    size = 80
    rounding = -1
    border_size = 2
    border_color = rgba(74, 122, 74, 0.5)
    position = 0, -320
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(200, 220, 200, 0.8)
    font_size = 16
    font_family = SF Pro Display Bold
    position = 0, -380
    halign = center
    valign = center
}

label {
    monitor =
    text =
    color = rgba(200, 220, 200, 0.6)
    font_size = 11
    font_family = SF Pro Display
    position = 0, -410
    halign = center
    valign = center
}
